_wandb:
    value:
        cli_version: 0.23.1
        e:
            nzeh9ho3hhv9im0ugdm0j8964452u87j:
                args:
                    - packages/cheapertraining/tests/unit/test_early_stopping.py::TestTinyModelPlateau::test_tiny_model_plateau_with_wandb
                    - -v
                    - -s
                codePath: .venv/bin/pytest
                codePathLocal: .venv/bin/pytest
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "982820896768"
                        used: "831412690944"
                email: levstamb@gmail.com
                executable: /home/lev/code/WrinkleFreeDev/.venv/bin/python3
                git:
                    commit: 53b25c92f32b4d68a7c1e3f066dd8dd88a8556a0
                    remote: git@github.com:DeepOpt-com/WrinkleFree-Monorepo.git
                gpu: NVIDIA GeForce RTX 3060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 4864
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3060 Ti
                      uuid: GPU-92cc2110-34e7-0ed8-b90b-53e0994f5494
                host: lev-B650M-C-Y1
                memory:
                    total: "15863517184"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/lev/code/WrinkleFreeDev/.venv/bin/pytest
                python: CPython 3.12.12
                root: /home/lev/code/WrinkleFreeDev
                startedAt: "2025-12-29T14:55:13.955809Z"
                writerId: nzeh9ho3hhv9im0ugdm0j8964452u87j
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 50
                - 105
            "2":
                - 1
                - 50
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
                - 62
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
test:
    value: plateau_detection
