_wandb:
    value:
        cli_version: 0.23.1
        e:
            u35w1u8y9ex8wgj5eoohk7vmzk05xpld:
                email: levstamb@gmail.com
                executable: /home/lev/code/WrinkleFree/WrinkleFree-CheaperTraining/.venv/bin/python3
                git:
                    commit: 41f27fe5cb6b7ca6fc5d7518bd675edc8c810a3b
                    remote: git@github.com:DeepOpt-com/WrinkleFree-CheaperTraining.git
                host: lev
                os: Linux-6.1.0-37-amd64-x86_64-with-glibc2.36
                program: <python with no main file>
                python: CPython 3.11.2
                root: /home/lev/code/WrinkleFree/WrinkleFree-CheaperTraining
                startedAt: "2025-12-26T20:33:48.253213Z"
                writerId: u35w1u8y9ex8wgj5eoohk7vmzk05xpld
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.2
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
eval_interval:
    value: 100
rebalance_interval:
    value: 200
steps:
    value: 1000
