_wandb:
    value:
        cli_version: 0.23.1
        e:
            wpbks43tb015nyw863769tqcjo9walk3:
                email: levstamb@gmail.com
                executable: /home/lev/code/WrinkleFree/WrinkleFree-CheaperTraining/.venv/bin/python3
                git:
                    commit: fbac4f72fa6d66407d1e2f04175c3c27613d8e6e
                    remote: git@github.com:DeepOpt-com/WrinkleFree-CheaperTraining.git
                host: lev
                os: Linux-6.1.0-37-amd64-x86_64-with-glibc2.36
                program: <python with no main file>
                python: CPython 3.11.2
                root: /home/lev/code/WrinkleFree/WrinkleFree-CheaperTraining
                startedAt: "2025-12-26T20:40:54.694981Z"
                writerId: wpbks43tb015nyw863769tqcjo9walk3
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.2
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
eval_interval:
    value: 200
lr:
    value: 0.0003
rebalance_interval:
    value: 300
steps:
    value: 3000
